### ISSUE TITLE
Potential improvements on Canada

### ISSUE THREAD

**Issue by HarukiKinoshita** [VictorCazanave/svg-maps#103]
Hi, I'm currently working on my project using [@svg-maps/Canada](https://github.com/VictorCazanave/svg-maps/tree/master/packages/canada). Do you have any plans to add a different map projection other than the existing one? It would be better if we have Lambert's projection of Canada. Thanks! 
https://en.wikipedia.org/wiki/File:Canada_(geolocalisation).svg

**Comment by VictorCazanave** [comment]
Hello,
I agree to add different map projections (e.g. `@svg-maps/canada.lambert-projection`), but I don't know when I can do 
that, because currently I don't have much free time to work on this project.
If you need it quickly, then fell free to contribute [creating a new map here](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md#adding-a-map-to-this-repository) or [on your own repository](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md#adding-a-map-from-an-external-respository)!

**Comment by HarukiKinoshita** [comment]
Thanks for your response! Let me see if I can be of help.

**Comment by VictorCazanave** [comment]
Resolved by https://github.com/VictorCazanave/svg-maps/pull/108
