### ISSUE TITLE
Merge France regions and departments into one file

### ISSUE THREAD

**Issue by gilles6** [VictorCazanave/svg-maps#47]
Could you merge France **regions** and **departments** into a unique file, maybe by creating a third `France` file ?

Interesting resources:
[data.gouv.fr : Cartes des régions et départements](https://www.data.gouv.fr/fr/datasets/cartes-des-regions-et-departements-issus-d-openstreetmap/)

**Comment by VictorCazanave** [comment]
If a map contains both regions and departments, I think the `<path>`s will overlap each other.

Then how such a map could be used? e.g. When the user points at a location, how do we know if he wants to point at the region or the department? 🤔

**Comment by gilles6** [comment]
You could set a variable to choose either `regions`, `departments` or `both`. In `both` case, `regions` selection depends on `departments` selection. What do you think about it ?

**Comment by VictorCazanave** [comment]
I think it may be good solution but it's a very specific use case and I'm not sure it should be in this repository, because the map won't be usable without a specific implementation.

Another solution might be to import both France regions and departments maps, then play with CSS/JS to display the map as needed.
Or you can create and publish your own mixed map with proper documentation (use case, implementation example...) and I'll be glad to add a link to this map.

**Comment by VictorCazanave** [comment]
Hi @gilles6,
Did you find a solution? I'd like to close this issue if there is nothing to do in this repository.
